name: Build, Tag, and Push Image

on:
  workflow_call:
    inputs:
      dockerfile-path:
        required: false
        type: string
        default: 'Dockerfile'
      image-name:
        required: true
        type: string
      image-tag:
        required: false
        type: string
        default: ' '
      azure-environment:
        type: string
        default: 'AzureCloud'
    secrets:
      AZURE_CREDENTIALS:
        required: true
      KVT_NAME:
        required: true
      ACR_LOGIN_SVR_SCT:
        required: true
      ACR_USR_SCT:
        required: true
      ACR_PWD_SCT:
        required: true
      CUSTOM_BUILD_ARGS:
        required: false

jobs:

  build-tag-push-image:
    name: Build, Tag, and Push Image to ACR
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set Docker Tag Based on Input/Branch
      id: dockertagstep
      run: |
        if [[ "${{github.ref}}" == "refs/heads/main" ]]; then
          echo "::set-output name=image-tag::main"
        fi

        if [[ "${{github.ref}}" == "refs/heads/develop" ]]; then
          echo "::set-output name=image-tag::develop"
        fi

        if [[ "${{github.ref}}" != "refs/heads/develop" && "${{github.ref}}" != "refs/heads/main" ]]; then
          echo "::set-output name=image-tag::qa"
        fi

        if [[ "${{inputs.image-tag}}" != " " ]]; then
          echo "::set-output name=image-tag::${{ inputs.image-tag }}"
        fi        
    
    - name: Install Azure cli
      run: |
        sudo apt-get install ca-certificates curl apt-transport-https lsb-release gnupg
        curl -sL https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/microsoft.gpg > /dev/null
        AZ_REPO=$(lsb_release -cs)
        echo "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ $AZ_REPO main" | sudo tee /etc/apt/sources.list.d/azure-cli.list
        sudo apt-get update
        sudo apt-get install azure-cli
    
    - uses: Azure/login@v1.4.3
      name: Login to Azure
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        environment: "AzureUSGovernment"
        enable-AzPSSession: false
        
    - uses: Azure/get-keyvault-secrets@v1
      name: Get Required Azure Secrets
      with:
        keyvault: "${{ secrets.KVT_NAME }}" # name of key vault in Azure portal
        secrets: '${{ secrets.ACR_LOGIN_SVR_SCT }}, ${{ secrets.ACR_USR_SCT }}, ${{ secrets.ACR_PWD_SCT }}'  # comma separated list of secret keys to fetch from key vault 
      id: azsecrets
      
    - name: Build the Docker image
      run: docker build . ${{ secrets.CUSTOM_BUILD_ARGS }} --file ${{ inputs.dockerfile-path }} --tag ${{ steps.azsecrets.outputs[secrets.ACR_LOGIN_SVR_SCT] }}/${{ inputs.image-name }}:${{ steps.dockertagstep.outputs.image-tag }}
      
    - uses: azure/docker-login@v1
      name: Login to ACR
      with:
        login-server: ${{ steps.azsecrets.outputs[secrets.ACR_LOGIN_SVR_SCT] }}
        username: ${{ steps.azsecrets.outputs[secrets.ACR_USR_SCT] }}
        password: ${{ steps.azsecrets.outputs[secrets.ACR_PWD_SCT] }}
    - name: Push to ACR
      run: |
        docker push ${{ steps.azsecrets.outputs[secrets.ACR_LOGIN_SVR_SCT] }}/${{ inputs.image-name }}:${{ steps.dockertagstep.outputs.image-tag }}
